### ISSUE TITLE
Setting the same identifier for 2 activations causes expiration date overwrite

### ISSUE THREAD

**Issue by stokrotkagucia** [ImmutableSoft/ImmutableEcosystem#5]
to recreate follow these steps
create 2 activations for the same product in my case prod2 but different expiration date standard and promotion
activation 0 
1231231311313112313131
actifvation 1 
1231231311313112313132
next change activation 1 to
1231231311313112313131
next change activation 1 to 
1231231311313112313132
this causes expiration date for the activation 1 overwrite
if products are different eg prod1 prod2
than nothing is happening both can have the same identifier
but when product names are the same and identifiers are set to the same value
overwrites are happening

**Comment by ImmutableSoft** [comment]
Thank you for the report. This procedure, to assign the activation id from one activation to the id of another, should "merge" the two activations into one activation of longer duration (combined expirations). After this "merge" activation 0 should have a later expiration time and activation 1 should be deactivated/removed. We will review your procedure and determine if this is a smart contract bug and if so, will do a formal assessment of severity.

**Comment by ImmutableSoft** [comment]
Assigned a risk of Medium and bounty details communicated offline. Thank you stokrotkagucia.
